window.updates={
	"others":{
		trash:["d2_mowang1.mp3","d2_mowang2.mp3","d2_mowang21.mp3","d2_mowang22.mp3","d2_zhuoyue41.mp3","d2_zhuoyue42.mp3","d2_mubei1","d2_mubei2","d2_mubei3"],
		load:function(lib,game,ui,get,ai,_status){
			var edit=lib.extensionMenu.extension_Dota2.edit;
	        var deletex=lib.extensionMenu.extension_Dota2.delete;
	        delete lib.extensionMenu.extension_Dota2.edit;
	        delete lib.extensionMenu.extension_Dota2.delete;
	        lib.extensionMenu.extension_Dota2.version={
	            "name":"扩展版本："+lib.config.noname_Dota2_version,
	            "clear":true,
	            "onclick":function(){
	                if(lib.d2_updates===undefined||lib.d2_updates.length==0) {
	                    alert('读取updates.js失败');
	                    return;
	                }
	                ui.click.configMenu();
	                changeLog();
	            },
	        };
	        lib.extensionMenu.extension_Dota2.update={
	            "name":"更新此扩展",
	            "clear":true,
	            "onclick":function(){
	                if(lib.d2_updates===undefined||lib.d2_updates.length==0) {
	                    alert('读取updates.js失败');
	                    return;
	                }
	                if(ui.noname_Dota2_update) {
	                    alert('正在更新...');
	                    return ;
	                }
	                var d2_nextVersion=lib.d2_nextVersion;
	                if(d2_nextVersion===undefined) {
	                    alert('无可用更新。');
	                    return ;
	                }

	                var list=lib.d2_updates[d2_nextVersion].files;
	                var tmp=lib.d2_updates[d2_nextVersion].next;
	                var lastestVersion=d2_nextVersion;
	                while(tmp) {
	                    var list2=lib.d2_updates[tmp].files;
	                    for(var i=0;i<list2.length;i++) {
	                        if(!list.contains(list2[i])) list.push(list2[i]);
	                    }
	                    lastestVersion=tmp;
	                    tmp=lib.d2_updates[tmp].next;
	                }
	                list.remove('CHANGELOG.MD');
	                list.remove('extension.js');
	                list.push('CHANGELOG.MD');
	                list.push('extension.js');

	                alert(list);return;

	                var list3=lib.d2_updates.others.trash;
	                if (list3&&list3.length) {
	                    for(var i=0;i<list3.length;i++){
	                        if(list.contains(list3[i])) list.remove(list3[i]);
	                    }
	                }

	                var n1=0,n2=list.length;
	                var finish=false;
	                ui.noname_Dota2_update=ui.create.system('Dota2:'+n1+'/'+n2,function(){
	                    if(finish) window.location.reload();
	                },true);
	                multiDownload(list,function(){
	                    n1++;
	                    ui.noname_Dota2_update.innerHTML='Dota2:'+n1+'/'+n2;
	                },null,function(){
	                    ui.noname_Dota2_update.innerHTML='Dota2更新完成';
	                    finish=true;
	                    game.saveConfig('noname_Dota2_version',lastestVersion);
	                })
	            },
	        };
	        lib.extensionMenu.extension_Dota2.clean={
	            "name":"清理多余文件",
	            "clear":true,
	            "onclick":function(){
	                if(lib.d2_updates===undefined||lib.d2_updates.length==0) {
	                    alert('读取updates.js失败');
	                    return;
	                }

	                var list=lib.d2_updates.others.trash;
	                if(list==undefined) alert('没有可清理的文件');
	                multiUnlink(list,null,null,function(){
	                    alert('清理完成');
	                });
	            },
	        };
	        lib.extensionMenu.extension_Dota2.edit=edit;
	        lib.extensionMenu.extension_Dota2.delete=deletex;

	        var changeLog=function(){
	            var dialog=ui.create.dialog('hidden');
	            dialog.style.height='calc(100%)';
	            dialog.style.width='calc(100%)';
	            dialog.style.left='0px';
	            dialog.style.top='0px';
	            dialog.classList.add('popped');
	            dialog.classList.add('static');
	            var div=ui.create.div('.menubutton.round','×',function(){
	                dialog.delete();
	            });
	            div.style.left='calc(50% - 35px)';
	            dialog.add(div);
	            for(var i in lib.d2_updates){
	                if (i=='others') continue;
	                var str=lib.config.noname_Dota2_version==i?'--当前版本':'';
	                dialog.addText(i+'('+lib.d2_updates[i].date+')'+str+'<br>',false);
	                if(lib.d2_updates[i].desc) dialog.addText(lib.d2_updates[i].desc,false);
	            };
	            ui.window.appendChild(dialog);
	        };
	        var needUpdate=function(){
	            ui.noname_Dota2_needUpdate=ui.create.system('Dota2扩展可更新',changeLog,true);
	        };
	        lib.d2_nextVersion=lib.d2_updates[lib.config.noname_Dota2_version].next;
	        if(lib.d2_nextVersion!=undefined)  {
                needUpdate();
            }
            lib.arenaReady.push(function(){
	            if(lib.d2_nextVersion!=undefined)  {
	                needUpdate();
	            }
	        });
		},
	},
	"1.6.0":{
		date:"2018.10.30",
		desc:"<li>新增武将：发条技师，冥界亚龙，风行者<br><li>不朽尸王、卓尔游侠技能调整<br><li>艾欧配音补全<br><li>bug修复",
		files:[
			"d2_clockwerk.jpg",
			"d2_danmu1.mp3",
			"d2_danmu2.mp3",
			"d2_danmu21.mp3",
			"d2_danmu22.mp3",
			"d2_fengxing_shan1.mp3",
			"d2_fengxing_shan2.mp3",
			"d2_fengxing1.mp3",
			"d2_fengxing2.mp3",
			"d2_fushi1.mp3",
			"d2_fushi2.mp3",
			"d2_guore1.mp3",
			"d2_guore2.mp3",
			"d2_guozai.mp3",
			"d2_jianglin.mp3",
			"d2_jiban.mp3",
			"d2_jiban1.mp3",
			"d2_jiban2.mp3",
			"d2_longdu1.mp3",
			"d2_longdu2.mp3",
			"d2_longdu3.mp3",
			"d2_qianyu1.mp3",
			"d2_qianyu2.mp3",
			"d2_shufu1.mp3",
			"d2_shufu2.mp3",
			"d2_viper.jpg",
			"d2_windranger.jpg",
			"d2_zhuoyue_disable1.mp3",
			"d2_zhuoyue_disable2.mp3",
			"d2_zuantou1.mp3",
			"d2_zuantou2.mp3",
			"die/d2_clockwerk.mp3",
			"die/d2_io.mp3",
			"die/d2_viper.mp3",
			"die/d2_windranger.mp3",
			"CHANGELOG.MD",
			"extension.js",
		],
	},
	"1.5.3":{
		date:"2018.10.24",
		desc:"<li>修复了在非兼容模式下每局游戏首次有角色受到伤害或回复体力时会卡住的bug<br><li>技能描述修正",
		files:["CHANGELOG.MD","extension.js"],
	},
	"1.5.2":{
		next:"1.5.3",
		date:"2018.10.21",
		desc:"<li>不朽尸王技能调整",
		files:["CHANGELOG.MD","extension.js"],
	},
	"1.5.1":{
		next:"1.5.2",
		date:"2018.10.21",
		desc:"<li>bug修复",
		files:["d2_mubei1.mp3","mubei2.mp3","d2_mubei3.mp3","CHANGELOG.MD","extension.js"],
	},
	"1.5.0":{
		next:"1.5.1",
		date:"2018.10.20",
		desc:"<li>新增武将：天涯墨客，剧毒术士，不朽尸王<li>影魔【魔王】改为【影压】<br><li>本扩展现在可以联机开启（可能会有更多bug）<br><li>抢夺神符所用的拼点现在无需弃置，而是回到各自手中<br><li>bug修复，以及一些其他改进",
		files:[
			"d2_duci1.mp3",
			"d2_duci2.mp3",
			"d2_fuhun1.mp3",
			"d2_fuhun2.mp3",
			"d2_fuhun3.mp3",
			"d2_ganran.mp3",
			"d2_ganran_immune.mp3",
			"d2_ganran_infected.mp3",
			"d2_judu1.mp3",
			"d2_judu2.mp3",
			"d2_moyong1.mp3",
			"d2_moyong2.mp3",
			"d2_mubei1.mp3",
			"d2_mubei2.mp3",
			"d2_mubei3.mp3",
			"d2_shenbi1.mp3",
			"d2_shenbi2.mp3",
			"d2_shibian1.mp3",
			"d2_shibian2.mp3",
			"d2_undying.jpg",
			"d2_venomancer.jpg",
			"d2_zhangqi1.mp3",
			"d2_zhangqi2.mp3",
			"d2_yingya1.mp3",
			"d2_yingya2.mp3",
			"announcer/kunkka/_d2_doubleKill.mp3",
			"announcer/kunkka/_d2_firstBlood.mp3",
			"announcer/kunkka/_d2_rampage.mp3",
			"announcer/kunkka/_d2_tripleKill.mp3",
			"announcer/kunkka/_d2_ultraKill.mp3",
			"announcer/tideHunter/_d2_doubleKill.mp3",
			"announcer/tideHunter/_d2_firstBlood.mp3",
			"announcer/tideHunter/_d2_rampage.mp3",
			"announcer/tideHunter/_d2_tripleKill.mp3",
			"announcer/tideHunter/_d2_ultraKill.mp3",
			"die/d2_grimStroke.mp3",
			"die/d2_undying.mp3",
			"die/d2_venomancer.mp3",
			"README.MD","CHANGELOG.MD","extension.js",
			],
	},
	"1.4.4":{
		next:"1.5.0",
		date:"2018.10.9",
		desc:"<li>bug修复",
		files:["CHANGELOG.MD","extension.js"],
	},
	"1.4.3":{
		next:"1.4.4",
		date:"2018.10.7",
		desc:"<li>编织者【回溯】重做<li>bug修复",
		files:["CHANGELOG.MD","extension.js"],
	},
	"1.4.2":{
		next:"1.4.3",
		date:"2018.10.3",
		desc:"<li>食人魔魔法师【炎术】描述修正",
		files:["CHANGELOG.MD","extension.js"],
	},
	"1.4.1":{
		next:"1.4.2",
		date:"2018.10.1",
		desc:"<li>bug修复",
		files:["CHANGELOG.MD","extension.js",],
	},
	"1.4.0":{
		next:"1.4.1",
		date:"2018.10.1",
		desc:"<li>新增武将：影魔，艾欧，编织者<br><li>新增锦囊：林肯法球，刃甲，诡计之雾，显影之尘<br><li>艾欧目前没有配音，反正你们也听不懂（其实是艾欧的配音提取出来居然是加密的）",
		files:[
			"d2_bladeMail.jpg",
			"d2_dust.jpg",
			"d2_grimStroke.jpg",
			"d2_huisu1.mp3",
			"d2_huisu2.mp3",
			"d2_io.jpg",
			"d2_lianji1.mp3",
			"d2_lianji2.mp3",
			"d2_linkensSphere.jpg",
			"d2_mowang1.mp3",
			"d2_mowang2.mp3",
			"d2_mowang21.mp3",
			"d2_mowang22.mp3",
			"d2_shadowFiend.jpg",
			"d2_smokeOfDeceit.jpg",
			"d2_souhun1.mp3",
			"d2_souhun2.mp3",
			"d2_souhun3.mp3",
			"d2_souhun4.mp3",
			"d2_suodi1.mp3",
			"d2_suodi2.mp3",
			"d2_wange1.mp3",
			"d2_wange2.mp3",
			"d2_weaver.jpg",
			"d2_shadowFiend.mp3",
			"d2_weaver.mp3",
			"CHANGELOG.MD","extension.js",
		],
	},
	"1.3.2":{
		next:"1.4.0",
		date:"2018.9.29",
		desc:"<li>修复了手机端不能正常运行的问题",
		files:["CHANGELOG.MD","extension.js"],
	},
	"1.3.1":{
		next:"1.3.2",
		date:"2018.9.16",
		desc:"<li>bug修复",
		files:["CHANGELOG.MD","extension.js"],
	},
	"1.3.0":{
		next:"1.3.1",
		date:"2018.9.15",
		desc:"<li>新增武将：幽鬼，殁境神蚀者，食人魔魔法师<br><li>新增装备：恐鳌之心，回音战刃，达贡之神力<br><li>新增玩法：神符（详情请看README.MD或游戏内帮助）<br><li>体验优化，现在你可以在游戏内更新此扩展了",
		files:[
			"d2_abaddon.jpg",
			"d2_aghanims.jpg",
			"d2_blessingAngel.jpg",
			"d2_bloodStone.jpg",
			"d2_boss_mage.jpg",
			"d2_centaurWarrunner.jpg",
			"d2_crystalMaiden.jpg",
			"d2_dagon1.jpg",
			"d2_dagon2.jpg",
			"d2_dagon3.jpg",
			"d2_dagon4.jpg",
			"d2_dagon5.jpg",
			"d2_drowRanger.jpg",
			"d2_dualSoul.jpg",
			"d2_earthSpirit.jpg",
			"d2_echoSabre.jpg",
			"d2_emberSpirit.jpg",
			"d2_forgedSpirit.jpg",
			"d2_heartOfTarrasque.jpg",
			"d2_houzihousun.jpg",
			"d2_invoker.jpg",
			"d2_legionCommander.jpg",
			"d2_lina.jpg",
			"d2_mage.jpg",
			"d2_megaCreep.jpg",
			"d2_monkeyKing.jpg",
			"d2_monkeyKingBar.jpg",
			"d2_observer.jpg",
			"d2_ogreMagi.jpg",
			"d2_oracle.jpg",
			"d2_outworldDevourer.jpg",
			"d2_phantomAssassin.jpg",
			"d2_phoenix.jpg",
			"d2_pudge.jpg",
			"d2_rubick.jpg",
			"d2_sentry.jpg",
			"d2_shadowDance.jpg",
			"d2_shivasGuard.jpg",
			"d2_skywrathMage.jpg",
			"d2_sniper.jpg",
			"d2_spectre.jpg",
			"d2_stormSpirit.jpg",
			"d2_supernova.jpg",
			"d2_terrorBlade.jpg",
			"d2_vengefulSpirit.jpg",
			"d2_wraithKing.jpg",
			"d2_zeus.jpg",
			"d2_aihen_ai1.mp3",
			"d2_aihen_ai2.mp3",
			"d2_aihen_hen1.mp3",
			"d2_aihen_hen2.mp3",
			"d2_andun1.mp3",
			"d2_andun2.mp3",
			"d2_ansha1.mp3",
			"d2_ansha2.mp3",
			"d2_ansha21.mp3",
			"d2_ansha22.mp3",
			"d2_aofa1.mp3",
			"d2_aofa2.mp3",
			"d2_aoshu1.mp3",
			"d2_aoshu2.mp3",
			"d2_aoshu21.mp3",
			"d2_aoshu22.mp3",
			"d2_bangji1.mp3",
			"d2_bangji2.mp3",
			"d2_bangji21.mp3",
			"d2_bangji22.mp3",
			"d2_benta1.mp3",
			"d2_benta2.mp3",
			"d2_bingfeng1.mp3",
			"d2_bingfeng2.mp3",
			"d2_binghuo_bing1.mp3",
			"d2_binghuo_bing2.mp3",
			"d2_binghuo_huo1.mp3",
			"d2_binghuo_huo2.mp3",
			"d2_bingjian1.mp3",
			"d2_bingjian2.mp3",
			"d2_canying1.mp3",
			"d2_canying2.mp3",
			"d2_canying21.mp3",
			"d2_canying22.mp3",
			"d2_chaozhenshengbo.mp3",
			"d2_chihun1.mp3",
			"d2_chihun2.mp3",
			"d2_chongsheng1.mp3",
			"d2_chongsheng2.mp3",
			"d2_chuancheng1.mp3",
			"d2_chuancheng2.mp3",
			"d2_chuancheng21.mp3",
			"d2_cihua1.mp3",
			"d2_cihua2.mp3",
			"d2_daoying1.mp3",
			"d2_daoying2.mp3",
			"d2_daozhi.mp3",
			"d2_diancimaichong.mp3",
			"d2_diyan1.mp3",
			"d2_diyan2.mp3",
			"d2_fanji1.mp3",
			"d2_fanji2.mp3",
			"d2_fanzhao1.mp3",
			"d2_fanzhao2.mp3",
			"d2_hanbingzhiqiang.mp3",
			"d2_hanyu1.mp3",
			"d2_hanyu2.mp3",
			"d2_hanyu21.mp3",
			"d2_hanyu22.mp3",
			"d2_hanyu31.mp3",
			"d2_hanyu32.mp3",
			"d2_houwang1.mp3",
			"d2_houwang2.mp3",
			"d2_houwang21.mp3",
			"d2_huanbian_sha.mp3",
			"d2_huanbian_shan.mp3",
			"d2_huanbian_wuxie.mp3",
			"d2_huangwu1.mp3",
			"d2_huangwu2.mp3",
			"d2_hunduan1.mp3",
			"d2_hunduan2.mp3",
			"d2_hundunyunshi.mp3",
			"d2_huodun1.mp3",
			"d2_huodun2.mp3",
			"d2_huoling1.mp3",
			"d2_huoling2.mp3",
			"d2_huoling21.mp3",
			"d2_huoling22.mp3",
			"d2_huoquan1.mp3",
			"d2_huoquan2.mp3",
			"d2_jietuo1.mp3",
			"d2_jietuo2.mp3",
			"d2_jietuo21.mp3",
			"d2_jingqi21.mp3",
			"d2_jingqi22.mp3",
			"d2_jingtong1.mp3",
			"d2_jingtong2.mp3",
			"d2_jingtong3.mp3",
			"d2_jisulengque.mp3",
			"d2_juedou1.mp3",
			"d2_juedou2.mp3",
			"d2_juji1.mp3",
			"d2_juji2.mp3",
			"d2_jushi1.mp3",
			"d2_jushi2.mp3",
			"d2_kuangfeng1.mp3",
			"d2_kuangfeng2.mp3",
			"d2_leiji1.mp3",
			"d2_leiji2.mp3",
			"d2_leiji21.mp3",
			"d2_leiji22.mp3",
			"d2_leiling1.mp3",
			"d2_leiling2.mp3",
			"d2_leiling21.mp3",
			"d2_leiling22.mp3",
			"d2_leishen1.mp3",
			"d2_leishen2.mp3",
			"d2_leiyun1.mp3",
			"d2_leiyun2.mp3",
			"d2_lingdongxunjie.mp3",
			"d2_mieshen1.mp3",
			"d2_mieshen2.mp3",
			"d2_minghuo1.mp3",
			"d2_minghuo2.mp3",
			"d2_miyin1.mp3",
			"d2_miyin2.mp3",
			"d2_mohu1.mp3",
			"d2_mohu2.mp3",
			"d2_mohua1.mp3",
			"d2_mohua2.mp3",
			"d2_niepan.mp3",
			"d2_polong1.mp3",
			"d2_polong2.mp3",
			"d2_qianggong1.mp3",
			"d2_qianggong2.mp3",
			"d2_qiangxijufeng.mp3",
			"d2_qihuan_fail1.mp3",
			"d2_qihuan_fail2.mp3",
			"d2_qihuan_scepter.mp3",
			"d2_qihuan1.mp3",
			"d2_qihuan2.mp3",
			"d2_ronglujingling.mp3",
			"d2_rougou_miss1.mp3",
			"d2_rougou_miss2.mp3",
			"d2_rougou1.mp3",
			"d2_rougou2.mp3",
			"d2_ruohua1.mp3",
			"d2_ruohua2.mp3",
			"d2_shengyao1.mp3",
			"d2_shengyao2.mp3",
			"d2_shizhi1.mp3",
			"d2_shizhi2.mp3",
			"d2_shuangren1.mp3",
			"d2_shuangren2.mp3",
			"d2_tayin1.mp3",
			"d2_tayin2.mp3",
			"d2_tayin3.mp3",
			"d2_tianqiu11.mp3",
			"d2_tianqiu12.mp3",
			"d2_tianqiu21.mp3",
			"d2_tianqiu22.mp3",
			"d2_tuling1.mp3",
			"d2_tuling2.mp3",
			"d2_tuling21.mp3",
			"d2_tuling22.mp3",
			"d2_woliu1.mp3",
			"d2_woliu2.mp3",
			"d2_xiandan1.mp3",
			"d2_xiandan2.mp3",
			"d2_xinxing.mp3",
			"d2_xiuqu1.mp3",
			"d2_xiuqu2.mp3",
			"d2_xiuqu21.mp3",
			"d2_xiuqu22.mp3",
			"d2_xuming.mp3",
			"d2_xuming1.mp3",
			"d2_xuming2.mp3",
			"d2_xunuo1.mp3",
			"d2_xunuo2.mp3",
			"d2_xunuo31.mp3",
			"d2_xunuo32.mp3",
			"d2_yangyanchongji.mp3",
			"d2_yanling.mp3",
			"d2_yanshu11.mp3",
			"d2_yanshu12.mp3",
			"d2_yanshu21.mp3",
			"d2_yanshu22.mp3",
			"d2_yingbi1.mp3",
			"d2_yingbi2.mp3",
			"d2_yongqi1.mp3",
			"d2_yongqi2.mp3",
			"d2_youlingmanbu.mp3",
			"d2_yuannu1.mp3",
			"d2_yuannu2.mp3",
			"d2_zheshe1.mp3",
			"d2_zheshe2.mp3",
			"d2_zheyu1.mp3",
			"d2_zheyu2.mp3",
			"d2_zhijie1.mp3",
			"d2_zhijie2.mp3",
			"d2_zhijie3.mp3",
			"d2_zhikao.mp3",
			"d2_zhuoyue1.mp3",
			"d2_zhuoyue2.mp3",
			"d2_zhuoyue41.mp3",
			"d2_zhuoyue42.mp3",
			"announcer/crystalMaiden/_d2_doubleKill.mp3",
			"announcer/crystalMaiden/_d2_firstBlood.mp3",
			"announcer/crystalMaiden/_d2_rampage.mp3",
			"announcer/crystalMaiden/_d2_tripleKill.mp3",
			"announcer/crystalMaiden/_d2_ultraKill.mp3",
			"announcer/default/_d2_doubleKill.mp3",
			"announcer/default/_d2_firstBlood.mp3",
			"announcer/default/_d2_rampage.mp3",
			"announcer/default/_d2_tripleKill.mp3",
			"announcer/default/_d2_ultraKill.mp3",
			"announcer/monkeyKing/_d2_doubleKill.mp3",
			"announcer/monkeyKing/_d2_firstBlood.mp3",
			"announcer/monkeyKing/_d2_rampage.mp3",
			"announcer/monkeyKing/_d2_tripleKill.mp3",
			"announcer/monkeyKing/_d2_ultraKill.mp3",
			"die/d2_abaddon.mp3",
			"die/d2_centaurWarrunner.mp3",
			"die/d2_crystalMaiden.mp3",
			"die/d2_drowRanger.mp3",
			"die/d2_earthSpirit.mp3",
			"die/d2_emberSpirit.mp3",
			"die/d2_invoker.mp3",
			"die/d2_legionCommander.mp3",
			"die/d2_lina.mp3",
			"die/d2_monkeyKing.mp3",
			"die/d2_oracle.mp3",
			"die/d2_phantomAssassin.mp3",
			"die/d2_phoenix.mp3",
			"die/d2_pudge.mp3",
			"die/d2_rubick.mp3",
			"die/d2_skywrathMage.mp3",
			"die/d2_sniper.mp3",
			"die/d2_spectre.mp3",
			"die/d2_stormSpirit.mp3",
			"die/d2_supernova.mp3",
			"die/d2_terrorBlade.mp3",
			"die/d2_vengefulSpirit.mp3",
			"die/d2_wraithKing.mp3",
			"die/d2_zeus.mp3",
			"CHANGELOG.MD",
			"README.MD",
			"extension.js",
		],
	},
	"1.0.0":{
		next:"1.3.0",
		date:"2018.7.6",
		desc:"<li>1.3.0之前的版本",
	},
};